site_docker_registry: rg.fr-par.scw.cloud/ecolo-web
site_client_default_port: 80
site_client_ssl_port: 443
site_client_image_environment: zerodechet_client_production
site_api_image_environment: zerodechet_server_production