- name: Creating application directory
  file:
    path: /opt/app
    state: directory
  become: yes

- name: Copying docker-compose configuration file
  template:
    src: templates/docker-compose.yml
    dest: /opt/app/docker-compose.yml
  become: yes

- name: Login to private docker registry
  docker_login:
    registry_url: '{{ site_docker_registry }}'
    username: '{{ scaleway_registry_login }}'
    password: '{{scaleway_secret_key }}'
- name: Run services
  docker_compose:
    project_name: 'zerodechet'
    project_src: /opt/app
    pull: yes
  become: yes