version: "3.3"
services:
  client:
    hostname: client
    image: '{{ site_docker_registry }}/{{ site_client_image_environment }}:latest'
    restart: always
    ports:
      - '{{ site_client_default_port }}:80'
      - '{{ site_client_ssl_port }}:443'
    networks:
      - client_net
      - server_net
      - strapi_net
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - /etc/letsencrypt/:/etc/letsencrypt/
  server:
    hostname: server
    image: '{{ site_docker_registry }}/{{ site_api_image_environment }}:latest'
    restart: always
    ports:
      - '{{ site_server_default_port }}:8080'
    environment:
      APP_ENV: prod
      APP_SECRET: 9b9156d2a9a86c6bdfd9a07102545fc3
      DATABASE_URL: 'mysql:{{ database_username }}:{{ database_password }}@mariadb_green:{{ database_port }}/{{ database_name }}'
      DATABASE_NAME: '{{ database_name }}'
    networks:
      - server_net
      - db_net
    depends_on:
      - mariadb
  mariadb:
    container_name: mariadb_green
    hostname: mariadb_green
    image: mariadb:10.5
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '{{ database_root_password }}'
      MYSQL_DATABASE: '{{ database_name }}'
      MYSQL_USER: '{{ database_username }}'
      MYSQL_PASSWORD: '{{ database_password }}'
    networks:
      - db_net  
    volumes:
      - /opt/data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10
  strapi:
    container_name: strapi
    hostname: strapi
    restart: always
    image: '{{ site_docker_registry }}/{{ site_strapi_image_environment }}:latest'
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: mysql
      DATABASE_HOST: strapi_db
      DATABASE_PORT: '{{ strapi_db_port }}'
      DATABASE_NAME: '{{ strapi_db_name }}'
      DATABASE_USERNAME: '{{ strapi_db_user }}'
      DATABASE_PASSWORD: '{{ strapi_db_pwd }}'
    ports:
      - '{{ strapi_app_port }}:1337'
    networks:
      - strapi_db_net
      - strapi_net
    volumes:
      - ./app:/srv/app
    depends_on:
      - strapi_db
    command: 'strapi start'
  strapi_db:
    image: mariadb:10.5
    container_name: strapi_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '{{ strapi_root_db_pwd }}'
      MYSQL_PASSWORD: '{{ strapi_db_pwd }}'
      MYSQL_USER: '{{ strapi_db_user }}'
      MYSQL_DATABASE: '{{ strapi_db_name }}'
    networks:
      - strapi_db_net
    volumes:
      - ./strapi_db_data:/var/lib/mysql
    ports:
      - '{{ strapi_db_port }}:3306'
networks:
  client_net:
  server_net:
  strapi_net:
  db_net:
  strapi_db_net:
volumes:
  strapi_db_data:
    driver: local