version: "3.3"
services:
  client:
    hostname: client
    image: '{{ site_docker_registry }}/{{ site_client_image_environment }}:latest'
    restart: always
    ports:
      - '{{ site_client_default_port }}:80'
      - '{{ site_client_ssl_port }}:443'
    networks:
      - client_net
    volumes:
      - ./nginx/:/etc/nginx/conf.d
networks:
  client_net: